import type { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "eva-demo-001",
    slug: "elegance-lace-bra",
    name: "سوتین دانتل Elegance",
    shortDescription: "ظریف، راحت و مناسب استفاده روزمره",
    description:
      "سوتین دانتل با طراحی ظریف و فرم راحت؛ انتخابی مینیمال برای استفاده روزمره.",
    categoryId: "bras",
    brand: "EVA MODE",
    basePrice: 890000,
    compareAtPrice: 1090000,
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isActive: true,
    createdAt: "2026-08-31T10:00:00.000Z",
    updatedAt: "2026-08-31T10:00:00.000Z",
  },
  {
    id: "eva-demo-002",
    slug: "soft-comfort-bra",
    name: "سوتین Soft Comfort",
    shortDescription: "راحتی روزانه با طراحی مینیمال",
    description:
      "مدلی سبک و راحت برای استفاده روزانه با طراحی ساده و ظریف.",
    categoryId: "bras",
    brand: "EVA MODE",
    basePrice: 760000,
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isActive: true,
    createdAt: "2026-08-31T10:05:00.000Z",
    updatedAt: "2026-08-31T10:05:00.000Z",
  },
  {
    id: "eva-demo-003",
    slug: "elegance-lingerie-set",
    name: "ست لباس زیر Elegance",
    shortDescription: "ترکیب ظرافت و راحتی",
    description:
      "ست زنانه با طراحی هماهنگ و جزئیات ظریف برای یک انتخاب خاص.",
    categoryId: "sets",
    brand: "EVA MODE",
    basePrice: 1290000,
    compareAtPrice: 1490000,
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isActive: true,
    createdAt: "2026-08-31T10:10:00.000Z",
    updatedAt: "2026-08-31T10:10:00.000Z",
  },
  {
    id: "eva-demo-004",
    slug: "daily-comfort-panty",
    name: "شورت Daily Comfort",
    shortDescription: "سبک، نرم و مناسب استفاده روزانه",
    description:
      "مدلی ساده و راحت برای استفاده روزانه با تمرکز بر آزادی حرکت.",
    categoryId: "underwear",
    brand: "EVA MODE",
    basePrice: 390000,
    isFeatured: false,
    isBestSeller: true,
    isNew: true,
    isActive: true,
    createdAt: "2026-08-31T10:15:00.000Z",
    updatedAt: "2026-08-31T10:15:00.000Z",
  },
  {
    id: "eva-demo-005",
    slug: "midnight-lace-set",
    name: "ست Midnight",
    shortDescription: "طراحی خاص با جزئیات ظریف",
    description:
      "مجموعه‌ای مینیمال با ظاهر متفاوت و جزئیات ظریف برای انتخابی خاص.",
    categoryId: "sets",
    brand: "EVA MODE",
    basePrice: 1490000,
    compareAtPrice: 1790000,
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isActive: true,
    createdAt: "2026-08-31T10:20:00.000Z",
    updatedAt: "2026-08-31T10:20:00.000Z",
  },
];