# Generated by Django 6.1.1 on 2026-09-05
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(max_length=50, unique=True, verbose_name="نامک"),
                ),
            ],
            options={
                "verbose_name": "دسته‌بندی",
                "verbose_name_plural": "دسته‌بندی‌ها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام محصول")),
                (
                    "slug",
                    models.SlugField(max_length=50, unique=True, verbose_name="نامک"),
                ),
                ("price", models.PositiveBigIntegerField(verbose_name="قیمت (تومان)")),
                (
                    "old_price",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="قیمت قبلی (تومان)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("image_url", models.URLField(blank=True, verbose_name="آدرس تصویر")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                        verbose_name="دسته‌بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-created_at"],
            },
        ),
    ]
