# Generated by Django 6.1.1
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="نام رنگ")),
                ("hex_code", models.CharField(blank=True, default="", max_length=7, verbose_name="کد رنگ")),
                ("image", models.ImageField(blank=True, null=True, upload_to="products/colors/", verbose_name="تصویر رنگ")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="colors", to="products.product", verbose_name="محصول")),
            ],
            options={
                "verbose_name": "رنگ محصول",
                "verbose_name_plural": "رنگ‌های محصول",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="productcolor",
            constraint=models.UniqueConstraint(fields=("product", "name"), name="unique_product_color_name"),
        ),
    ]
