# Generated by Django 6.1.1 on 2026-09-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_gallery_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='سایز')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایزها',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر هاور'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر اصلی'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/colors/', verbose_name='تصویر هاور این رنگ'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/colors/', verbose_name='تصویر این رنگ'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hover_image_url',
            field=models.URLField(blank=True, verbose_name='تصویر هاور (آدرس قدیمی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='تصویر اصلی (آدرس قدیمی)'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='hover_image_url',
            field=models.URLField(blank=True, verbose_name='تصویر هاور این رنگ (آدرس قدیمی)'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='تصویر این رنگ (آدرس قدیمی)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='آدرس تصویر قدیمی'),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product', verbose_name='محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sizes', to='products.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'سایز محصول',
                'verbose_name_plural': 'سایزهای محصول',
                'constraints': [models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size')],
            },
        ),
    ]
