# Generated by Django 6.1.1
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productcolor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductColorImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="products/color-galleries/", verbose_name="تصویر")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("color", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="products.productcolor", verbose_name="رنگ")),
            ],
            options={
                "verbose_name": "تصویر گالری رنگ",
                "verbose_name_plural": "تصاویر گالری رنگ",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
